// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqAdkFwrpZWKalOcSohAqAV3Z24gYNtIY',
    appId: '1:20078393900:web:95c78f924133557fd16f89',
    messagingSenderId: '20078393900',
    projectId: 'eros-dateapp',
    authDomain: 'eros-dateapp.firebaseapp.com',
    storageBucket: 'eros-dateapp.firebasestorage.app',
    measurementId: 'G-XDFKQ65LMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA38RsiDXawUi8JjiEpvSIN0BdiJ_ZbMbw',
    appId: '1:20078393900:android:4bb007948196b5c6d16f89',
    messagingSenderId: '20078393900',
    projectId: 'eros-dateapp',
    storageBucket: 'eros-dateapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK755kEo7en-nMT0CusClV-L5nyYS5Rc4',
    appId: '1:20078393900:ios:49b0d1e578cd882ed16f89',
    messagingSenderId: '20078393900',
    projectId: 'eros-dateapp',
    storageBucket: 'eros-dateapp.firebasestorage.app',
    iosBundleId: 'com.piyasa.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK755kEo7en-nMT0CusClV-L5nyYS5Rc4',
    appId: '1:20078393900:ios:49b0d1e578cd882ed16f89',
    messagingSenderId: '20078393900',
    projectId: 'eros-dateapp',
    storageBucket: 'eros-dateapp.firebasestorage.app',
    iosBundleId: 'com.piyasa.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqAdkFwrpZWKalOcSohAqAV3Z24gYNtIY',
    appId: '1:20078393900:web:b61d40cbeb8ba006d16f89',
    messagingSenderId: '20078393900',
    projectId: 'eros-dateapp',
    authDomain: 'eros-dateapp.firebaseapp.com',
    storageBucket: 'eros-dateapp.firebasestorage.app',
    measurementId: 'G-QPYSCV9YEF',
  );
}
